# Generated by Django 4.2.6 on 2023-10-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoverapp', '0002_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingreds',
            field=models.CharField(max_length=255, verbose_name='ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=models.CharField(max_length=255, verbose_name='nutrition'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.CharField(max_length=255, verbose_name='steps'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(max_length=255, verbose_name='tags'),
        ),
    ]
