# Generated by Django 4.2.6 on 2023-10-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoverapp', '0004_testtable2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable2',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
