# Generated by Django 4.2.6 on 2023-10-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoverapp', '0005_alter_testtable2_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='testTable3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
        migrations.DeleteModel(
            name='testTable2',
        ),
    ]
