# Generated by Django 4.2.6 on 2023-10-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discoverapp', '0006_testtable3_delete_testtable2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testTable3',
        ),
    ]
