# Generated by Django 4.2.6 on 2023-10-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discoverapp', '0007_delete_testtable3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
