# Generated by Django 4.2.6 on 2023-10-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoverapp', '0008_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('minutes', models.IntegerField(verbose_name='minutes')),
                ('submitted', models.DateField(verbose_name='submitted')),
                ('tags', models.CharField(max_length=255, verbose_name='tags')),
                ('nutrition', models.CharField(max_length=255, verbose_name='nutrition')),
                ('steps', models.CharField(max_length=255, verbose_name='steps')),
                ('step_num', models.IntegerField(verbose_name='n_steps')),
                ('ingreds', models.CharField(max_length=255, verbose_name='ingredients')),
                ('ingred_num', models.IntegerField(verbose_name='n_ingredients')),
            ],
        ),
    ]
