# Generated by Django 4.2.6 on 2023-10-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discoverapp', '0009_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
