# Generated by Django 4.2.6 on 2023-10-31 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discoverapp', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
